name: Proyecto de Fisica I UCM
description: Visualizaciones de fisica universitaria
theme: jekyll-theme-cayman
author: Omar Olivares
author_email: ofjolivares@gmail.com
markdown: kramdown
permalink: pretty
github_username: ofou
